In [1]:
import pandas as pd
import numpy as np
import csv
from datetime import datetime

In [2]:
#read the file
df = pd.read_csv('laws_and_incentives (Apr 7 2022).csv')
df.head()

,Law Id,State,Title,Text,Enacted Date,Amended Date,Recent?,Sequence Number,Type,Agency,Significant Update Date,Expired Date,Archived Date,Repealed Date,Topic,Technology Categories,Incentive Categories,Regulation Categories,User Categories,References
0,284,US,Congestion Mitigation and Air Quality (CMAQ) I...,The CMAQ Program provides funding to state dep...,2005-08-10 00:00:00 UTC,2021-11-15 00:00:00 UTC,False,54.0,Incentives,U.S. Department of Transportation,2021-11-29 21:00:16 UTC,NaN,NaN,NaN,NaN,BIOD|ETH|ELEC|HY|IR|NG|PHEV|LPG,GNT,NaN,STATION|FLEET|GOV,https://www.congress.gov/public-laws/117th-con...
1,288,US,Clean Cities Coalition Network,The mission of Clean Cities Coalition Network ...,NaN,NaN,False,21.0,Programs,U.S. Department of Energy,NaN,NaN,NaN,NaN,NaN,AFTMKTCONV|BIOD|ETH|ELEC|EFFEC|HEV|HY|IR|NG|NE...,GNT|OTHER,NaN,STATION|AFP|PURCH|MAN|FLEET|GOV|IND,NaN
2,317,US,State Energy Program (SEP) Funding,The SEP provides grants to states to assist in...,NaN,2021-11-15 00:00:00 UTC,False,26.0,Incentives,U.S. Department of Energy,2021-11-29 21:33:02 UTC,NaN,NaN,NaN,NaN,BIOD|ETH|ELEC|EFFEC|HY|NG|PHEV|LPG,GNT,NaN,OTHER,https://www.congress.gov/public-laws/117th-con...
3,323,US,Clean School Bus,The U.S. Environmental Protection Agency\'s (E...,NaN,2021-11-15 00:00:00 UTC,True,33.0,Incentives,U.S. Environmental Protection Agency,2022-03-24 15:26:06 UTC,NaN,NaN,NaN,NaN,AFTMKTCONV|BIOD|ETH|ELEC|EFFEC|HY|IR|NG|PHEV|LPG,GNT,NaN,FLEET|GOV,https://www.congress.gov/public-laws/117th-con...
4,324,US,Clean Construction and Agriculture,Clean Construction is a voluntary program that...,NaN,NaN,False,34.0,Programs,U.S. Environmental Protection Agency,NaN,NaN,NaN,NaN,NaN,BIOD|ELEC|HEV|HY|NG|PHEV|LPG,GNT,NaN,PURCH|FLEET|OTHER,NaN

In [3]:
#show the columns and choose what we need (State,Type)
list(df)

['Law Id',
 'State',
 'Title',
 'Text',
 'Enacted Date',
 'Amended Date',
 'Recent?',
 'Sequence Number',
 'Type',
 'Agency',
 'Significant Update Date',
 'Expired Date',
 'Archived Date',
 'Repealed Date',
 'Topic',
 'Technology Categories',
 'Incentive Categories',
 'Regulation Categories',
 'User Categories',
 'References']

In [4]:
df=df.drop(['Law Id',

 'Title',
 'Text',
 'Enacted Date',
 'Amended Date',
 'Recent?',
 'Sequence Number',

 'Agency',
 'Significant Update Date',
 'Expired Date',
 'Archived Date',
 'Repealed Date',
 'Topic',
 'Technology Categories',
 'Incentive Categories',
 'Regulation Categories',
 'User Categories',
 'References'],axis=1)

In [5]:
list=[]
for index, row in df.iterrows():
    if df.iloc[index,0] == 'US':
        list.append(index)
df = df.drop(list,axis=0)

In [6]:
State = np.sort(['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','Florida','Georgia','Hawaii',
             'Idaho','Illinois','Indiana','Iowa','Kansa','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan',
             'Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York',
             'North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas',
             'Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming'])
Postal_Abbr = ['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH',
    'OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY']

In [7]:
for index in range(50):
    df = df.replace(Postal_Abbr[index], State[index])

In [8]:
df

          State                        Type
18      Arizona            State Incentives
19      Arizona            State Incentives
20   California            State Incentives
21   California  Utility/Private Incentives
22   California        Laws and Regulations
..          ...                         ...
971    Colorado  Utility/Private Incentives
972      Nevada  Utility/Private Incentives
973      Nevada  Utility/Private Incentives
974   Wisconsin            State Incentives
975  New Mexico            State Incentives

[929 rows x 2 columns]

In [9]:
Type = np.sort(df['Type'].unique())
Type

array(['Laws and Regulations', 'State Incentives',
       'Utility/Private Incentives'], dtype=object)

In [14]:
new_df = pd.DataFrame(columns=Type)
new_df.insert(loc=0,column='State',value=State)
new_df = new_df.set_index('State')

In [15]:
new_df.head()

           Laws and Regulations State Incentives Utility/Private Incentives
State
Alabama                     NaN              NaN                        NaN
Alaska                      NaN              NaN                        NaN
Arizona                     NaN              NaN                        NaN
Arkansas                    NaN              NaN                        NaN
California                  NaN              NaN                        NaN

In [22]:
for state in State:
    for tp in Type:
        count=0
        for index, row in df.iterrows():
            if df['State'][index] == state and df['Type'][index] == tp:
                count += 1
        new_df.at[state,tp] = count
new_df['Total'] = new_df.iloc[:,0:2].sum(axis=1)

In [24]:
new_df.head()

,Laws and Regulations,State Incentives,Utility/Private Incentives,Total
State,,,,
Alabama,3,2,3,5.0
Alaska,2,0,4,2.0
Arizona,9,5,10,14.0
Arkansas,4,1,1,5.0
California,47,40,46,87.0

In [25]:
# Now we have cleanned data, save it into processed file
path = '../../processed/policy_state.csv'
new_df.to_csv(path)